# Generated by Django 4.2.22 on 2025-06-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcasdicominatorcontent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flexpage",
            options={"verbose_name": "flex page", "verbose_name_plural": "flex pages"},
        ),
    ]
