# Generated by Django 4.2.22 on 2025-06-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancerLabel",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("uid", models.CharField(max_length=128)),
                ("cancer_type", models.CharField(max_length=64)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("stage", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DicomTag",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("uid", models.CharField(max_length=128)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("study", "Study"),
                            ("series", "Series"),
                            ("instance", "Instance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("tag", models.CharField(max_length=16)),
                ("tag_name", models.CharField(max_length=128)),
                ("vr", models.CharField(blank=True, max_length=4, null=True)),
                ("value", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("sop_instance_uid", models.CharField(max_length=128, unique=True)),
                ("image_number", models.IntegerField(blank=True, null=True)),
                ("slice_thickness", models.FloatField(blank=True, null=True)),
                (
                    "pixel_spacing",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "image_orientation",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("patient_id", models.CharField(max_length=64, unique=True)),
                ("patient_sex", models.CharField(blank=True, max_length=10, null=True)),
                ("patient_birth_date", models.DateField(blank=True, null=True)),
                ("other_attributes", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PatientIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("series_instance_uid", models.CharField(max_length=128, unique=True)),
                ("series_number", models.IntegerField(blank=True, null=True)),
                ("series_description", models.TextField(blank=True, null=True)),
                ("modality", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "body_part_examined",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("series_date", models.DateField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "software_versions",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("study_instance_uid", models.CharField(max_length=128, unique=True)),
                ("study_date", models.DateField(blank=True, null=True)),
                ("study_description", models.TextField(blank=True, null=True)),
                (
                    "accession_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
