# Generated by Django 4.2.23 on 2025-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcasdicominatortags", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["patient_id"], name="jpllabcasdi_patient_9ae88e_idx"
            ),
        ),
    ]
