# Generated by Django 4.2.23 on 2025-06-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcasdicominatortags", "0002_patient_jpllabcasdi_patient_9ae88e_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="software_versions",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
