# Generated by Django 4.2.23 on 2025-07-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        (
            "jpllabcasdicominatortags",
            "0004_remove_dicomtag_tag_remove_dicomtag_uid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TagIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TagFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(help_text="Keyword for the tag", max_length=64),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name of the tag",
                        max_length=200,
                    ),
                ),
                (
                    "tag_group",
                    models.PositiveIntegerField(
                        default=0, help_text="Group number for the tag"
                    ),
                ),
                (
                    "tag_element",
                    models.PositiveIntegerField(
                        default=0, help_text="Element number for the tag"
                    ),
                ),
                (
                    "frequency",
                    models.BigIntegerField(
                        default=0, help_text="Number of times this tag has been seen"
                    ),
                ),
            ],
            options={
                "verbose_name": "DICOM Tag Frequency",
                "verbose_name_plural": "DICOM Tag Frequencies",
                "indexes": [
                    models.Index(
                        fields=["keyword"], name="jpllabcasdi_keyword_6f86ff_idx"
                    ),
                    models.Index(
                        fields=["frequency"], name="jpllabcasdi_frequen_f06bda_idx"
                    ),
                ],
                "unique_together": {("tag_group", "tag_element")},
            },
        ),
        migrations.CreateModel(
            name="SurveyedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(help_text="Path to the file", max_length=2048),
                ),
            ],
            options={
                "verbose_name": "Surveyed File",
                "verbose_name_plural": "Surveyed Files",
                "indexes": [
                    models.Index(
                        fields=["file_path"], name="jpllabcasdi_file_pa_9cbd55_idx"
                    )
                ],
            },
        ),
    ]
